device: cuda
# folders
log_path: logs/log.txt
result_path: results/
data_dir: ../data

# preprocessing
num_examples: -1
max_len: -1

# tokenizer
min_freq: -1

# training
lr: !!float 1e-3
num_epochs: 1
train_batch_size: 64
max_grad_norm: 1.0
num_warmups: 0.06

# inference
max_len_trg: 50
test_batch_size: 64

# model
emb_dim: 768
hidden_dim: 256
unit_dim: 128 # for BahdanauAttention
