device: cuda
# folders
log_path: logs/log.txt
result_path: results/
data_dir: ../data

# preprocessing
num_examples: -1
train_max_len: 50
lowercase: false

# tokenizer
min_freq: 5

# training
lr: !!float 1e-3
num_epochs: 1
train_batch_size: 32
max_grad_norm: 1.0
num_warmups: 0.06

# inference
max_len_trg: 50
test_batch_size: 4
#beam
beam_size: 3
beam_max_length: 20 # should be smaller than pe_max_seq_len

# model
dropout: 0.1
d_model: 512
d_ff: 2048
n_heads: 8
pe_max_seq_len: 200

n_encoder_layers: 6
n_decoder_layers: 6
